import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SplashScreen from "@/components/SplashScreen";
import Navbar from "@/components/Navbar";
import { ArticlesProvider } from "@/context/ArticlesContext";
import { getArticles, getCategories } from "@/lib/fetcher";
import CTA from "@/components/CTA";
import { Suspense } from "react";
import ConsultationModal from "@/components/ConsultationModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Big.dk website animation clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [articles, categories] = await Promise.all([
    getArticles(),
    getCategories(),
  ]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ArticlesProvider
          initialArticles={articles}
          initialCategories={categories}
        >
          <Navbar />
          <SplashScreen>{children}</SplashScreen>
          <CTA />
          <Suspense fallback={null}>
            <ConsultationModal />
          </Suspense>
        </ArticlesProvider>
      </body>
    </html>
  );
}
